/**
 * STEP 36G.1 Test Suite — Real-Runtime Multilingual Canonical Case Loss
 * & Follow-Up Question/Answer Semantic Linking
 *
 * Validates:
 * - TEST A: Sinhala urinary initial case ("මුත්රා කරනකොට වේදනාවක් තියෙනවා")
 *           -> positive: ["painful urination"], domain: "urinary", stays intact after follow-up turn #1
 * - TEST B: Sinhala blood-in-urine question + No ("නැත")
 *           -> negative: ["no blood in urine"], existing "painful urination" preserved
 * - TEST C: Sinhala descriptive urinary answer ("මුත්රා කරනකොට වේදනාවක් තියෙනවා, සාමාන්යයට වඩා නිතර මුත්රා කරන්නත් ඕන වෙනවා")
 *           -> positive: ["painful urination", "frequent urination"]
 * - TEST D: English rash (itchy red rash, no lip swelling, no difficulty breathing, both arms, today, dermatology)
 * - TEST E: Sinhala rash semantic parity
 * - TEST F: Generic question + explicit Sinhala symptom ("අත් දෙකේම රතු පාට කැසීමක් ඇති රෑෂ් එකක් තියෙනවා")
 * - TEST G: Generic short Yes ("ඔව්") -> Derived: []
 * - TEST H: Ambiguous multi-concept short Yes ("Do you have dizziness, vomiting, or weakness?" -> "Yes") -> Derived: []
 * - TEST I: Canonical preservation across non-positive follow-up turn
 * - TEST J: Neurological regression ("weakness in both feet for 1 week") -> domain neurology, context/duration survive all turns
 */

const assert = require('assert');
const clinicalCaseService = require('../src/services/clinicalCaseService');
const geminiConversationService = require('../src/services/geminiConversationService');
const geminiTranslationService = require('../src/services/geminiTranslationService');

console.log('====================================================');
console.log('STARTING STEP 36G.1 VERIFICATION TEST SUITE');
console.log('====================================================\n');

let passedTests = 0;
let totalTests = 0;

function runTest(name, fn) {
  totalTests++;
  try {
    fn();
    console.log(`✅ [PASS] ${name}`);
    passedTests++;
  } catch (err) {
    console.error(`❌ [FAIL] ${name}`);
    console.error(err);
  }
}

// -------------------------------------------------------------
// TEST A — Sinhala urinary initial case
// -------------------------------------------------------------
runTest('TEST A — Sinhala urinary initial case ("මුත්රා කරනකොට වේදනාවක් තියෙනවා")', () => {
  const input = "මුත්රා කරනකොට වේදනාවක් තියෙනවා";

  const initialCase = clinicalCaseService.buildCanonicalClinicalCase({
    symptoms: [input],
  });

  const profile = clinicalCaseService.buildClinicalProfile(initialCase);
  console.log('Test A Initial Case:', JSON.stringify(initialCase, null, 2));
  console.log('Test A Profile:', JSON.stringify(profile, null, 2));

  assert(
    initialCase.positiveSymptoms.includes('painful urination'),
    `Must extract "painful urination" (got: ${JSON.stringify(initialCase.positiveSymptoms)})`
  );
  assert.strictEqual(profile.clinicalDomain, 'urinary', `Domain must be "urinary" (got: ${profile.clinicalDomain})`);

  // Simulate Turn 1 where patient answers a follow-up with no new positives (e.g. fever: "no")
  const turn1 = [
    {
      question: "Do you have a fever?",
      answer: "no",
      canonicalQuestion: "Do you have a fever?",
      canonicalAnswer: "no",
      clinicalConcept: "fever",
    },
  ];

  const caseAfterTurn1 = clinicalCaseService.buildCanonicalClinicalCase({
    symptoms: [input],
    conversation: turn1,
    positiveSymptoms: initialCase.positiveSymptoms,
    negativeFindings: initialCase.negativeFindings,
    context: initialCase.context,
    duration: initialCase.duration,
  });

  console.log('Test A After Turn 1:', JSON.stringify(caseAfterTurn1, null, 2));
  const profileAfterTurn1 = clinicalCaseService.buildClinicalProfile(caseAfterTurn1);

  assert(
    caseAfterTurn1.positiveSymptoms.includes('painful urination'),
    'Existing "painful urination" must remain intact after turn 1'
  );
  assert(
    caseAfterTurn1.negativeFindings.includes('no fever'),
    'Must include "no fever" after turn 1'
  );
  assert.strictEqual(profileAfterTurn1.clinicalDomain, 'urinary', 'Domain must remain "urinary" after turn 1');
});

// -------------------------------------------------------------
// TEST B — Sinhala blood-in-urine question + No
// -------------------------------------------------------------
runTest('TEST B — Sinhala blood-in-urine question + No ("නැත")', () => {
  const input = "මුත්රා කරනකොට වේදනාවක් තියෙනවා";

  // Question generated by Gemini in English, displayed in Sinhala
  const canonicalQ = "Have you noticed any blood in your urine?";
  const displayQ = "ඔබේ මුත්රා සමඟ රුධිරය පිටවීමක් ඔබ දුටුවාද?";
  const answer = "නැත";

  // Test question normalization
  const normalizedQ = geminiTranslationService.normalizeQuestionTextToEnglish(displayQ);
  console.log('Test B Normalized Q from Sinhala display:', normalizedQ);
  assert.strictEqual(
    normalizedQ,
    "Have you noticed any blood in your urine?",
    'Must normalize Sinhala blood in urine question to canonical English'
  );

  const turn = [
    {
      question: displayQ,
      answer: answer,
      canonicalQuestion: canonicalQ,
      canonicalAnswer: "no",
      clinicalConcept: "blood in urine",
    },
  ];

  const canonicalCase = clinicalCaseService.buildCanonicalClinicalCase({
    symptoms: [input],
    conversation: turn,
    positiveSymptoms: ['painful urination'],
  });

  console.log('Test B Result:', JSON.stringify(canonicalCase, null, 2));

  assert(
    canonicalCase.positiveSymptoms.includes('painful urination'),
    'Existing "painful urination" MUST remain positive'
  );
  assert(
    canonicalCase.negativeFindings.includes('no blood in urine'),
    `negativeFindings must include "no blood in urine" (got: ${JSON.stringify(canonicalCase.negativeFindings)})`
  );
});

// -------------------------------------------------------------
// TEST C — Sinhala descriptive urinary answer
// -------------------------------------------------------------
runTest('TEST C — Sinhala descriptive urinary answer', () => {
  const answer = "මුත්රා කරනකොට වේදනාවක් තියෙනවා, සාමාන්යයට වඩා නිතර මුත්රා කරන්නත් ඕන වෙනවා";

  const turn = [
    {
      question: "Can you describe what you are feeling?",
      answer: answer,
      canonicalQuestion: "Can you describe what you are feeling?",
      canonicalAnswer: answer,
    },
  ];

  const canonicalCase = clinicalCaseService.buildCanonicalClinicalCase({
    symptoms: [],
    conversation: turn,
  });

  console.log('Test C Result:', JSON.stringify(canonicalCase, null, 2));

  assert(
    canonicalCase.positiveSymptoms.includes('painful urination'),
    `Must extract "painful urination" from descriptive Sinhala answer (got: ${JSON.stringify(canonicalCase.positiveSymptoms)})`
  );
  assert(
    canonicalCase.positiveSymptoms.includes('frequent urination'),
    `Must extract "frequent urination" from descriptive Sinhala answer (got: ${JSON.stringify(canonicalCase.positiveSymptoms)})`
  );
});

// -------------------------------------------------------------
// TEST D — English rash
// -------------------------------------------------------------
runTest('TEST D — English rash (itchy red rash, both arms, today, no lip swelling, no difficulty breathing)', () => {
  const input = "I developed an itchy red rash on both arms today. I have no swelling of my lips and no difficulty breathing.";

  const canonicalCase = clinicalCaseService.buildCanonicalClinicalCase({
    symptoms: [input],
  });

  const profile = clinicalCaseService.buildClinicalProfile(canonicalCase);
  console.log('Test D Result:', JSON.stringify(profile, null, 2));

  assert(canonicalCase.positiveSymptoms.includes('itchy red rash'), 'Must extract itchy red rash');
  assert(canonicalCase.negativeFindings.includes('no lip swelling'), 'Must extract no lip swelling');
  assert(canonicalCase.negativeFindings.includes('no difficulty breathing'), 'Must extract no difficulty breathing');
  assert(!canonicalCase.positiveSymptoms.some(s => s.toLowerCase().includes('swelling')), 'Must NOT contain positive swelling');
  assert(canonicalCase.context.includes('both arms'), 'Must include both arms in context');
  assert.strictEqual(canonicalCase.duration, 'today', 'Duration must be today');
  assert.strictEqual(profile.clinicalDomain, 'dermatology', 'Domain must be dermatology');
});

// -------------------------------------------------------------
// TEST E — Sinhala rash semantic parity
// -------------------------------------------------------------
runTest('TEST E — Sinhala rash semantic parity', () => {
  const siInput = "අද අත් දෙකේම රතු පාට කැසීමක් ඇති රෑෂ් එකක් ආවා. තොල් ඉදිමීමක්වත් හුස්ම ගන්න අපහසුතාවයක්වත් නැහැ";

  const canonicalCase = clinicalCaseService.buildCanonicalClinicalCase({
    symptoms: [siInput],
  });

  const profile = clinicalCaseService.buildClinicalProfile(canonicalCase);
  console.log('Test E Result:', JSON.stringify(profile, null, 2));

  assert(canonicalCase.positiveSymptoms.includes('itchy red rash'), 'Must extract itchy red rash for Sinhala');
  assert(canonicalCase.negativeFindings.includes('no lip swelling'), 'Must extract no lip swelling for Sinhala');
  assert(canonicalCase.negativeFindings.includes('no difficulty breathing'), 'Must extract no difficulty breathing for Sinhala');
  assert(!canonicalCase.positiveSymptoms.some(s => s.toLowerCase().includes('swelling')), 'Must NOT contain positive swelling');
  assert(canonicalCase.context.includes('both arms'), 'Must include both arms in context');
  assert.strictEqual(canonicalCase.duration, 'today', 'Duration must be today');
  assert.strictEqual(profile.clinicalDomain, 'dermatology', 'Domain must be dermatology');
});

// -------------------------------------------------------------
// TEST F — Generic question + explicit Sinhala symptom
// -------------------------------------------------------------
runTest('TEST F — Generic question + explicit Sinhala symptom ("අත් දෙකේම රතු පාට කැසීමක් ඇති රෑෂ් එකක් තියෙනවා")', () => {
  const turn = [
    {
      question: "Can you describe your symptoms?",
      answer: "අත් දෙකේම රතු පාට කැසීමක් ඇති රෑෂ් එකක් තියෙනවා",
      canonicalQuestion: "Can you describe your symptoms?",
      canonicalAnswer: "අත් දෙකේම රතු පාට කැසීමක් ඇති රෑෂ් එකක් තියෙනවා",
    },
  ];

  const canonicalCase = clinicalCaseService.buildCanonicalClinicalCase({
    symptoms: [],
    conversation: turn,
  });

  console.log('Test F Result:', JSON.stringify(canonicalCase, null, 2));

  assert(
    canonicalCase.positiveSymptoms.includes('itchy red rash'),
    `Must extract "itchy red rash" from answer (got: ${JSON.stringify(canonicalCase.positiveSymptoms)})`
  );
  assert(
    canonicalCase.context.includes('both arms'),
    `Must extract "both arms" from answer (got: ${JSON.stringify(canonicalCase.context)})`
  );
});

// -------------------------------------------------------------
// TEST G — Generic short Yes ("ඔව්") -> Derived: []
// -------------------------------------------------------------
runTest('TEST G — Generic short Yes ("ඔව්") -> Derived: []', () => {
  const turn = [
    {
      question: "Are there any other changes?",
      answer: "ඔව්",
      canonicalQuestion: "Are there any other changes?",
      canonicalAnswer: "yes",
    },
  ];

  const canonicalCase = clinicalCaseService.buildCanonicalClinicalCase({
    symptoms: ["headache"],
    conversation: turn,
  });

  console.log('Test G Positives:', canonicalCase.positiveSymptoms);
  assert.deepStrictEqual(
    canonicalCase.positiveSymptoms,
    ['headache'],
    'Generic short Yes must not invent symptoms'
  );
});

// -------------------------------------------------------------
// TEST H — Ambiguous multi-concept short Yes -> Derived: []
// -------------------------------------------------------------
runTest('TEST H — Ambiguous multi-concept short Yes -> Derived: []', () => {
  const turn = [
    {
      question: "Do you have dizziness, vomiting, or weakness?",
      answer: "Yes",
      canonicalQuestion: "Do you have dizziness, vomiting, or weakness?",
      canonicalAnswer: "yes",
    },
  ];

  const canonicalCase = clinicalCaseService.buildCanonicalClinicalCase({
    symptoms: ["headache"],
    conversation: turn,
  });

  console.log('Test H Positives:', canonicalCase.positiveSymptoms);
  assert.deepStrictEqual(
    canonicalCase.positiveSymptoms,
    ['headache'],
    'Ambiguous multi-concept Yes must not invent dizziness, vomiting, or weakness'
  );
});

// -------------------------------------------------------------
// TEST I — Canonical preservation across non-positive follow-up turn
// -------------------------------------------------------------
runTest('TEST I — Canonical preservation across non-positive follow-up turn', () => {
  const basePositives = ['painful urination'];
  const baseNegatives = ['no back pain'];
  const baseDuration = '3 days';

  const turn = [
    {
      question: "Do you have a fever?",
      answer: "No",
      canonicalQuestion: "Do you have a fever?",
      canonicalAnswer: "no",
      clinicalConcept: "fever",
    },
  ];

  const merged = clinicalCaseService.buildCanonicalClinicalCase({
    symptoms: ["painful urination"],
    conversation: turn,
    positiveSymptoms: basePositives,
    negativeFindings: baseNegatives,
    duration: baseDuration,
  });

  console.log('Test I Merged Result:', JSON.stringify(merged, null, 2));

  assert(merged.positiveSymptoms.includes('painful urination'), 'Must retain positive "painful urination"');
  assert(merged.negativeFindings.includes('no back pain'), 'Must retain negative "no back pain"');
  assert(merged.negativeFindings.includes('no fever'), 'Must add new negative "no fever"');
  assert.strictEqual(merged.duration, '3 days', 'Must retain duration "3 days"');
});

// -------------------------------------------------------------
// TEST J — Neurological regression ("weakness in both feet for 1 week")
// -------------------------------------------------------------
runTest('TEST J — Neurological regression ("weakness in both feet for 1 week")', () => {
  const input = "weakness in both feet for 1 week";

  const case0 = clinicalCaseService.buildCanonicalClinicalCase({ symptoms: [input] });
  const prof0 = clinicalCaseService.buildClinicalProfile(case0);

  assert.strictEqual(prof0.clinicalDomain, 'neurology', 'Initial domain must be neurology');
  assert(case0.positiveSymptoms.some(s => s.includes('weakness')), 'Must extract weakness');
  assert(case0.context.some(c => c.includes('feet')), 'Must extract feet context');
  assert.strictEqual(case0.duration, '1 week', 'Duration must be 1 week');

  // Turn 1
  const turn1 = [{ question: "Have you noticed any numbness or tingling in your feet?", answer: "Yes", canonicalQuestion: "Have you noticed any numbness or tingling in your feet?", canonicalAnswer: "yes" }];
  const case1 = clinicalCaseService.buildCanonicalClinicalCase({ symptoms: [input], conversation: turn1, positiveSymptoms: case0.positiveSymptoms, context: case0.context, duration: case0.duration });

  // Turn 2
  const turn2 = [...turn1, { question: "Have you noticed any difficulty with your balance or walking?", answer: "No", canonicalQuestion: "Have you noticed any difficulty with your balance or walking?", canonicalAnswer: "no" }];
  const case2 = clinicalCaseService.buildCanonicalClinicalCase({ symptoms: [input], conversation: turn2, positiveSymptoms: case1.positiveSymptoms, context: case1.context, duration: case1.duration });

  // Turn 3
  const turn3 = [...turn2, { question: "Do you have any back pain?", answer: "No", canonicalQuestion: "Do you have any back pain?", canonicalAnswer: "no" }];
  const case3 = clinicalCaseService.buildCanonicalClinicalCase({ symptoms: [input], conversation: turn3, positiveSymptoms: case2.positiveSymptoms, context: case2.context, duration: case2.duration });

  console.log('Test J Final Case after 3 turns:', JSON.stringify(case3, null, 2));

  assert(case3.positiveSymptoms.some(s => s.includes('weakness')), 'Weakness must survive all turns');
  assert(case3.context.some(c => c.includes('feet')), 'Feet context must survive all turns');
  assert.strictEqual(case3.duration, '1 week', 'Duration must survive all turns');
  assert(case3.negativeFindings.includes('no balance or walking difficulty'), 'Must extract no balance or walking difficulty');
  assert(case3.negativeFindings.includes('no back pain'), 'Must extract no back pain');
});

console.log('\n====================================================');
console.log(`TEST RESULTS: ${passedTests} / ${totalTests} TESTS PASSED`);
console.log('====================================================\n');

if (passedTests === totalTests) {
  process.exit(0);
} else {
  process.exit(1);
}
